export enum RoutesDocu {
  Colors = '/docu/info/colors',
  Config = '/docu/info/config',
  CustomizeComponents = '/docu/info/customize-components',
  Install = '/docu/info/install',
  LayoutAndTypography = '/docu/info/layout-and-typography',
  ThemeGenerator = '/docu/info/theme-generator',
  Themes = '/docu/info/themes',
  Use = '/docu/info/use',

  Button = '/docu/components/actions/button',
  Dropdown = '/docu/components/actions/dropdown',
  Modal = '/docu/components/actions/modal',
  Swap = '/docu/components/actions/swap',

  Checkbox = '/docu/components/forms/checkbox',
  Radio = '/docu/components/forms/radio',
  Range = '/docu/components/forms/range',
  Rating = '/docu/components/forms/rating',
  Select = '/docu/components/forms/select',
  TextInput = '/docu/components/forms/text-input',
  Textarea = '/docu/components/forms/textarea',
  Toggle = '/docu/components/forms/toggle',
  Label = '/docu/components/forms/label',

  Artboard = '/docu/components/layout/artboard',
  ButtonGroup = '/docu/components/layout/button-group',
  Divider = '/docu/components/layout/divider',
  Drawer = '/docu/components/layout/drawer',
  Footer = '/docu/components/layout/footer',
  Hero = '/docu/components/layout/hero',
  Indicator = '/docu/components/layout/indicator',
  InputGroup = '/docu/components/layout/input-group',
  Mask = '/docu/components/layout/mask',
  Stack = '/docu/components/layout/stack',
  Spinner = '/docu/components/layout/spinner',

  Code = '/docu/components/mockups/code',
  Phone = '/docu/components/mockups/phone',
  Window = '/docu/components/mockups/window',

  Breadcrumbs = '/docu/components/navigation/breadcrumbs',
  Link = '/docu/components/navigation/link',
  Menu = '/docu/components/navigation/menu',
  Navbar = '/docu/components/navigation/navbar',
  Pagination = '/docu/components/navigation/pagination',
  Steps = '/docu/components/navigation/steps',
  Tab = '/docu/components/navigation/tab',
  NavLink = '/docu/components/navigation/nav-link',

  Table = '/docu/components/tables/table',

  Alert = '/docu/components/ui_elements/alert',
  Avatar = '/docu/components/ui_elements/avatar',
  Badge = '/docu/components/ui_elements/badge',
  Card = '/docu/components/ui_elements/card',
  Carousel = '/docu/components/ui_elements/carousel',
  Collapse = '/docu/components/ui_elements/collapse',
  Countdown = '/docu/components/ui_elements/countdown',
  Kbd = '/docu/components/ui_elements/kbd',
  Progress = '/docu/components/ui_elements/progress',
  RadialProgress = '/docu/components/ui_elements/radial-progress',
  Stat = '/docu/components/ui_elements/stat',
  Tooltip = '/docu/components/ui_elements/tooltip',
}
